### ISSUE TITLE
Approach for including filters?

### ISSUE THREAD

**Issue by mokargas** [lean/phaser-es6-webpack#12]
This is more a question on approach

Filters aren't bundled with Phaser normally, but they are available in the NPM distribution

What would be the best way to include them via Webpack (I'm new to it)? I can include them the old fashioned way with game.load.script, but it would be nice to simply do something like 'import Filtername from Filters'

**Comment by leandr0ck** [comment]
Actually you could not import that filters. They are not bundled like a module
