### ISSUE TITLE
Games don't play audio in production

### ISSUE THREAD

**Issue by crazyyi** [lean/phaser-es6-webpack#23]
I have an "audio" folder in "assets" folder. My audio files reside in that folder and my game references audio files in the folder. When I run "dev" my game plays background music but when I run "deploy" and click the index.html file my game has no sound. How should I configure webpack to play the background music in production? Or do I need to change any directory structure?

**Comment by microcipcip** [comment]
You're probably opening the index.html file directly, you should use a proper server like MAMP or XAMP so that when you open your file in the url bar you see something like `http://localhost/my-project` instead of `file:///C:/Users/MyUserName/Desktop/index.html`

**Comment by leandr0ck** [comment]
Anyway this is not a bug, this is not concerned with the project. Maybe you could find a proper solution with the webpack community.
