### ISSUE TITLE
EXACT_FIT scaling issue

### ISSUE THREAD

**Issue by llzionll** [lean/phaser-es6-webpack#26]
please take a look at this post.

https://github.com/photonstorm/phaser/issues/2537

Same issue happens in this boiler-plate.

In this case, modify "main.js" like 

-from-
super(width, height, Phaser.AUTO, 'content', null) 

-to-
super(width, height, Phaser.AUTO, '', null)

erasing 4th parameter will work.

sorry for bad english and thank you for good boiler plate like this.

**Comment by leandr0ck** [comment]
what is the issue? please could you paste your source? If you are modifing the scale, that is not a problem with the proyect itself, because this proyect it is agnostic about scale.
