### ISSUE TITLE
Using plugins

### ISSUE THREAD

**Issue by GeorgThomassen** [lean/phaser-es6-webpack#30]
Hi,

Thanks for a great boilerplate!

I wondered how one would go around using plugins when using this boilerplate?

I'm trying with the "phaser-plugin-isometric" plugin but it could be any plugin.

Thanks in advance

**Comment by leandr0ck** [comment]
You can include any npm package. But in this case, that plugin has not published as a module, you could include in the normal way like a script in your html.

**Comment by GeorgThomassen** [comment]
I went with another approach and added the git repo as a npm dependency by adding `"phaser-plugin-isometric": "git+https://github.com/lewster32/phaser-plugin-isometric.git"` to the package.json

Then added the module to the vendor file in the webpack config.

And finally added the plugin in the preload method in the Boot state. I don't know if that is best practice but I guess that is a Phaser question! 😊
