### ISSUE TITLE
Ninja Physics

### ISSUE THREAD

**Issue by stephanedemotte** [lean/phaser-es6-webpack#31]
Could be cool to have Ninja physics available out of the box :)

Juste a idea, because i want to use it, and it's painful to get started with :/

Thanks !

**Comment by leandr0ck** [comment]
Ninja physics it's included in Phaser for default. What do you need? An example?

**Comment by stephanedemotte** [comment]
<img width="830" alt="screen shot 2017-06-15 at 11 59 14 am" src="https://user-images.githubusercontent.com/2158130/27190318-1a01e516-51c2-11e7-929c-733fa9444a62.png">

Don't find it in node_modules, anyway i use P2 physics now :)

Thanks a lot for this great starterkit !
