### ISSUE TITLE
How fast is this compared to phaser alone?

### ISSUE THREAD

**Issue by jr69** [lean/phaser-es6-webpack#33]
The phaser-es6-webpack file I have from cloning this repo is ~100MB and I am assuming that's the base project. Compared to a hello world of phaser, which just includes the phaser.js file and an index.html file.

If this is put on some aws instance, or some remote server, would that mean that players would have to download all these files before being able to play (thus taking longer)?

Edit: How would one also deploy the build? I tried running 'npm run deploy' but nothing happens

**Comment by leandr0ck** [comment]
Please check the source of the index.html file. That will resolve all of your questions
