### ISSUE TITLE
Uncaught Error: Cannot find module 

### ISSUE THREAD

**Issue by bee0806** [lean/phaser-es6-webpack#42]
> phaser-es6-webpack-1.0\src\main.js"
    at webpackMissingModule (_math-scale.js:18)
    at Object.<anonymous> (_math-scale.js:18)
    at __webpack_require__ (bootstrap 8158fcd1685397aac32a:54)
    at webpackJsonpCallback (bootstrap 8158fcd1685397aac32a:25)
    at bundle.js:1

hi there i've get that error when try to run development server using `npm run dev` , am i missing any file?. thanks

**Comment by leandr0ck** [comment]
Hi. Have you modified the project after cloning it?

**Comment by bee0806** [comment]
not yet ,  just cloning your repo and try to run, but that errors appears

**Comment by bee0806** [comment]
here is the errors in command bash when i run `npm run dev` 
![es6](https://user-images.githubusercontent.com/25424955/31325591-e7d72830-ace8-11e7-89be-07c6f3ee406f.png)

**Comment by leandr0ck** [comment]
Could you make a fresh install in another location? 
What is that "!!ES6" in the path?

**Comment by leandr0ck** [comment]
closed for inactivity
