### ISSUE TITLE
VS Code is not using IntelliSense

### ISSUE THREAD

**Issue by niklasfink** [lean/phaser-es6-webpack#44]
Hi, I can't get VS Code IntelliSense (autocompletion) to work properly with your setup.
I thought this should be enable automatically, out of the box? How can I make it work? 🙂

![image](https://user-images.githubusercontent.com/1809301/31413862-15814976-ae67-11e7-83f7-cf5bda0af090.png)

**Comment by necrosmash** [comment]
I managed to get the desired behaviour by changing

`import Phaser from 'phaser'`

to

`import 'phaser'`

in the files that include that import:

- main.js
- Mushroom.js
- Boots.js
- Game.js
- Splash.js

For the record, I don't require a `/// <reference` line, like you have.

The demo still runs fine with these changes. Is there any benefit to specifying the name `Phaser` when performing the import?

**Comment by leandr0ck** [comment]
With Phaser 2.x the library is not a module itself. We must wait for the release 3 for a real module import. Maybe this is your issues
