### ISSUE TITLE
I will add cordova to this project and a command prompt to configure this bootstrap

### ISSUE THREAD

**Issue by RenaudRohlinger** [lean/phaser-es6-webpack#47]
Hey,

I am going to add cordova to my project who is based on this bootstrap so I wanted to add it to this project. 
Basically I think I will add a prompt command to configure the bootstrap, update the package.json, the new config.xml (cordova) && index.html (why not).
Then, I'll just update the documentation.

Just one question,
Is that ok if I add a "www" folder next to the dist folder ? (cordova required)

**Comment by leandr0ck** [comment]
It is that "www" folder, the build folder?

**Comment by RenaudRohlinger** [comment]
The "www" folder will be another build folder (but this one won't be .gitignore because we need some setup) next to "dist" with the cordova architecture. When we will npm run build it will generate files in the dist and we will use CopyWebpackPlugin to duplicate them to the www/dist folder.

Then with the command "cordova run android (or ios)" it will generate a "platforms" and a "plugins" folder (.gitignore)

**Comment by leandr0ck** [comment]
Cool. I think this will be a nice feature, so go ahead.

**Comment by leandr0ck** [comment]
PR: #48
