### ISSUE TITLE
proposal: use webpack-dev-server to replace browser-sync

### ISSUE THREAD

**Issue by markx** [lean/phaser-es6-webpack#50]
I personally find webpack-dev-server better for the reasons:
1. simpler
2. when run `npm run dev`, it doesn't generate files into `dist`, which makes better sense to me because IMO `dist` should only contain files for distribution.

**Comment by RenaudRohlinger** [comment]
Hi !
BrowserSync has better features, allows for multiple device testing out of the box, includes a great admin panel for more control and bandwidth throttling which is helpful to test for speed and loading. Furthemore we could just set another folder like "tmp" for the dev which would be .gitignored but actually, I see no reason to switch.

**Comment by markx** [comment]
Yeah I never used those features, but they could be helpful. Thanks!
