### ISSUE TITLE
Loading Assets on Build

### ISSUE THREAD

**Issue by jackmead515** [lean/phaser-es6-webpack#53]
My question is, how? Unfortunately, I cannot find anything to help me so I have resorted to the issues.

**Comment by RenaudRohlinger** [comment]
I don't understand, the build task will generate an index.html at the root of the project who will point on the existing assets so there is nothing different with dev ?

**Comment by jackmead515** [comment]
That's what I thought! Or I assumed as much. But I'm getting an error. Let me go into detail...
My Splash state is in /src/states/Spash.js and I load the assets as such "assets/images/whatever.png". My assets folder is right where it should be at "/assets/images" at the same level as the src and dist.

Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at file:///Users/jackmead/Documents/Workspace/mygame/assets/images/loader-bg.png may not be loaded.

**Comment by leandr0ck** [comment]
Jack, what is your operating system?

**Comment by jackmead515** [comment]
macOS Sierra 10.12.6 using Google Chrome

**Comment by RenaudRohlinger** [comment]
I have absolutely no idea, I tried on a clean project and everything works fine. I'm assuming you are just launching the index.html from the "src/" folder and not in the root folder.

**Comment by leandr0ck** [comment]
Are you accesing to a localhost or you just open the html?

**Comment by jackmead515** [comment]
You know, as an avid developer, I must say, I feel ashamed. But, I have a good excuse. I was working on this at 3:30, on a Friday, after a full day of programming at work. Yes, it was a CORS problem because I was simply opening the index.html file. Solution: use a server dumby. I'd consider this issue closed.

**Comment by leandr0ck** [comment]
Dude, take a breathe and relax. Thanks for using the project.
