### ISSUE TITLE
Explicit `chunks` line may break webpack by omitting other dependencies

### ISSUE THREAD

**Issue by mrisher** [lean/phaser-es6-webpack#58]
My `webpack.prod.conf.js` is from a newer template than yours; in my version, webpack attempts to split the webpack runtime into a `manifest.js` file. When I blindly copied your explicit `chunks` statement into my template, it caused the generated `index.html` to exclude this manifest, which resulted in webpack not getting loaded (you get a runtime JS error like "_webpackjsonp is not defined_"

The solution is to explicitly mention `manifest` in the `chunks` block.

Here's the code from my vue-cli template:
```javascript
    // extract webpack runtime and module manifest to its own file in order to
    // prevent vendor hash from being updated whenever app bundle is updated
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      minChunks: Infinity
    }),
```

I'd recommend changing the line
```javascript
chunks: ['vendor', 'app']
```
to
```javascript
chunks: ['manifest', 'vendor', 'app']
```
in this file 
https://github.com/lean/phaser-es6-webpack/blob/28b3021e52bcbd0ce425b9ce593a94bde06aef2a/webpack.config.js#L38

**Comment by leandr0ck** [comment]
@mrisher  please, could you show your webpack configuration?
