### ISSUE TITLE
deploy creates wrong file paths

### ISSUE THREAD

**Issue by eladonline** [lean/phaser-es6-webpack#59]
When I'm running the game in dev mode everything works fine 
But after deployment, I enter build directory and run the index file.
And getting errors of files not found .
It seems that the 'deploy' doesn't arrange the paths right .
> Wrong path   
![image](https://user-images.githubusercontent.com/20336964/34815751-3eeef44c-f6bb-11e7-86ba-06b352da9eaa.png)

> Right path!
![image](https://user-images.githubusercontent.com/20336964/34815804-7e40a910-f6bb-11e7-9b1e-b55958064ebf.png)

This is the main directory path:
#### C:\Users\admin\Desktop\zelda diamond collector\phaser-es6-webpack

Here is the hierarchy: 
![image](https://user-images.githubusercontent.com/20336964/34816046-4d9730b2-f6bc-11e7-80e5-6f5d7147a370.png)

**Comment by eladonline** [comment]
I manage to overcome the problem, but the issue should still be fixed.
The file that imported the assets, had the path "../../assets/etc..." which works fine in dev env .
Now, the vendor.bundle sits in "root/js", and opening it from index file will try to go to 
"not exist/not exist/root" 
I solved it by changing "../../assets/etc..." to "./assets/etc..." but I guess it isn't a good behavior

**Comment by leandr0ck** [comment]
Thanks @eladonline. This is not a good behavior. I will see it

**Comment by leandr0ck** [comment]
@eladonline seems like you are not using a web server. Your paths does not be "file://".
Please, try to serve your files with Browsersyc.
Run inside the build folder: `browser-sync start --server`
