### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by zh-wowtv** [lean/phaser-es6-webpack#6]
Got the following warning message:

> WARNING in ./~/phaser/build/custom/p2.js
> Critical dependencies:
> 24:397-404 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
>  @ ./~/phaser/build/custom/p2.js 24:397-404

What could be wrong? Thanks

**Comment by leandr0ck** [comment]
Hi. Nothing is wrong. The warning message is from webpack telling to us "hey this is a custom build".
You could use normally, the real problem is with the phaser packages, but not with the project itself
