### ISSUE TITLE
Remove loading of bangers font by default in main boot class.

### ISSUE THREAD

**Issue by JakeLaCombe** [lean/phaser-es6-webpack#62]
I was looking through the code of the Boot state, and saw that it was trying to load the bangers font family. (https://github.com/lean/phaser-es6-webpack/blob/master/src/states/Boot.js#L14). Lately, the font has been taking a while to download, causing this game to to freeze on the loading fonts page.

Since this is the starting template for a game to build using webpack and phaser, perhaps it could be ideal if we remove the default behavior of loading a font library?

**Comment by leandr0ck** [comment]
thanks for the suggestion. Done 
https://github.com/lean/phaser-es6-webpack/commit/5e01f3dbf5e75d685ee59b91b45b90ec17d5faeb

**Comment by JakeLaCombe** [comment]
Thanks man!
