### ISSUE TITLE
Can't clone git

### ISSUE THREAD

**Issue by ghost** [lean/phaser-es6-webpack#66]
It's weird. I tried to clone the .git to my directory and got an error on cmd prompt:

fatal: unable to access 'http:s//github.com/lean/phaser-es6-webpack.git': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:t1sv1 alert protocol version

It prevents me to download the depo for some reason.

Any idea why?

**Comment by leandr0ck** [comment]
check the protocol, seems wrong "htt:s"
