### ISSUE TITLE
How to use phaser plugins

### ISSUE THREAD

**Issue by henriquecustodia** [lean/phaser-es6-webpack#67]
Hi, I would like know how to use the [phaser-sound-analyser](https://github.com/KaktusFlame/phaser-sound-analyser) with this boilerplate. I'm getting some error on try. 

I'm saw that [comment](https://github.com/lean/phaser-es6-webpack/issues/30#issuecomment-304658133) but it's confuse for me. 

Can somebody shows a explicit solution with an examples if possible?

Thanks!

**Comment by RenaudRohlinger** [comment]
I did it for a project long time ago like that :
```
import '../audio/Audio' 

const soundAnalyse = this.game.plugins.add(new Phaser.Plugin.SoundAnalyse(this))
this.soundAnalyseSprite = soundAnalyse.add.soundAnalyseSprite(0, 0, this.game.width, this.game.height, 'holyother', false, this._onDecodeFinish, this)
```

where my Audio file was just a copy of https://github.com/KaktusFlame/phaser-sound-analyser/blob/master/js/plugin/SoundAnalyse/SoundAnalyse.js file

**Comment by henriquecustodia** [comment]
@RenaudROHLINGER Thank you!
