### ISSUE TITLE
Phaser plugins integration

### ISSUE THREAD

**Issue by Huljo** [lean/phaser-es6-webpack#74]
Hello,

I try to use some Phaser plugins but nothing works for me.

My first attempt was with [Slick-UI](https://github.com/Flaxis/slick-ui).

As suggested [here](https://github.com/lean/phaser-es6-webpack/issues/30) I just added the plugin inside my vendors bundle and added it in my game using the preload function (src/states/Boot.js) but I get an unexpected result : 

*webpack.config.js* :
```` javascript
var slickui = path.join(__dirname, '/node_modules/slick-ui/dist/slick-ui.min.js')
[...]
  entry: {
    app: [...],
    vendor: [..., 'slickui']
  },
module: {
    rules: [...
      { test: /slick-ui\.min\.js/, use: ['expose-loader?SlickUi'] } // SlickUi = {<empty object>} in browser
    ]
  },
  resolve: {
    alias: { ...
      'slickui': slickui
    }
  }
````
*src/index.html* :
```` html
    <script>
      var SlickUI;
    </script>
````

*src/states/Boot.js* :
```` javascript
preload() {
 SlickUI = this.game.plugins.add(Phaser.Plugin.SlickUI);
}
````

*src/states/Boot.js* :
```` javascript
create() {
 var panel;
 SlickUI.add(panel = new SlickUI.Element.Panel(8, 8, 150, this.game.height - 16)); // Throw an Error : "Uncaught TypeError: Cannot read property 'Panel' of undefined"
}
````

In the plugin demo ([here](http://slick-ui.com/preview/menu.html)) the plugin object looks like this (Plugin added to the game): 

````
> SlickUI
{
  Container: Object
  Element: Object // < The property I want to use
  Keyboard: Object
  namespace: Function
}
````

But in my case I get a different object (Plugin added to the game): 
````
> SlickUI
{
  active: true,
  defaultRenderer: Object,
  game: Game,
  hasPostRender: true,
  hasPostUpdate: false,
  hasPreUpdate: true,
  hasRender: true,
  hasUpdate: true,
  parent: Phaser.PluginManager,
  renderer: Object,
  visible: true,
  __proto__: Phaser.Plugin
}
````

Slick-Ui add itselft to Phaser's plugins global object : 
Phaser.Plugin.SlickUI // I can reach this one
It need Phaser.Plugin.prototype to properly initiate the plugin (before using it in game)

Any help welcome, Im stuck with this issue since a few days..

**Comment by leandr0ck** [comment]
https://github.com/Flaxis/slick-ui/issues/26 
please check if that library is working as npm module. If is not, you could include in the html (old school mode)
