### ISSUE TITLE
Info.plist file not found.

### ISSUE THREAD

**Issue by whiteadi** [lean/phaser-es6-webpack#75]
Hi,

first: super nice boilerplate, I use it and it works in the browser, but when want to run it on xcode simulator, like so:

yarn
yarn cordova
cordova platform add ios
cordova run ios

I get:
/Users/adrianalbu/git/kickballs/platforms/ios/build/emulator/KickBalls.app/Info.plist file not found.

PS: here is my repo I did used and mentioned your awesome one ;) :
https://github.com/whiteadi/kickballs

**Comment by whiteadi** [comment]
Forgot to say I have it on Mac, xcode simulator version 10.0 and also before the actual file not found it also displays the message: No target specified for emulator. Deploying to iPhone-XS-Max, 12.0 simulator
when runing cordova run ios

**Comment by whiteadi** [comment]
Hi, can you please tell me why you closed this?

**Comment by leandr0ck** [comment]
Sorry. I closed because I think that the problem is not related with the project itself. It is more a environment configuration issue. What do you think about?

**Comment by whiteadi** [comment]
Yes I guess it is was hoping you encountered this before, I am not so experienced with the setup, but of course... :)
